import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js';
import { z } from 'zod';
import {
  MAX_AUDIO_CHUNKS,
  MAX_SPEECH_CONTEXT_CHARS,
  analyzeVoiceNote,
  sanitizeProviderErrorMessage,
} from '../../lib/voice-processing';

const APP_NAME = 'voice-note-studio';
const APP_VERSION = '1.0.0';
const TOOL_RESOURCE_URI = 'ui://voice-note-studio/guide.html';

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers':
    'Content-Type, mcp-session-id, Last-Event-ID, last-event-id, mcp-protocol-version',
  'Access-Control-Expose-Headers': 'mcp-session-id, mcp-protocol-version',
};

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 300;

function buildToolGuideHtml(appUrl) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Voice Note Studio</title>
    <style>
      :root {
        color-scheme: light dark;
        --bg-start: #0f172a;
        --bg-end: #1f2937;
        --card: rgba(15, 23, 42, 0.88);
        --border: rgba(255, 255, 255, 0.14);
        --text: #f8fafc;
        --muted: rgba(248, 250, 252, 0.78);
        --accent: #f97316;
        --accent-soft: rgba(249, 115, 22, 0.16);
        --shadow: 0 28px 60px rgba(15, 23, 42, 0.35);
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
        min-height: 100vh;
        font-family: "SF Pro Display", "Segoe UI", sans-serif;
        color: var(--text);
        background:
          radial-gradient(circle at top left, rgba(251, 191, 36, 0.28), transparent 34%),
          radial-gradient(circle at top right, rgba(56, 189, 248, 0.16), transparent 28%),
          linear-gradient(150deg, var(--bg-start), var(--bg-end));
      }

      main {
        padding: 24px;
      }

      .card {
        max-width: 720px;
        margin: 0 auto;
        padding: 28px;
        border-radius: 28px;
        background: var(--card);
        border: 1px solid var(--border);
        box-shadow: var(--shadow);
        backdrop-filter: blur(18px);
      }

      .eyebrow {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        margin-bottom: 16px;
        padding: 8px 12px;
        border-radius: 999px;
        background: var(--accent-soft);
        color: #fdba74;
        font-size: 12px;
        letter-spacing: 0.18em;
        text-transform: uppercase;
      }

      h1 {
        margin: 0 0 12px;
        font-size: clamp(32px, 5vw, 48px);
        line-height: 0.96;
        letter-spacing: -0.04em;
      }

      p {
        margin: 0;
        color: var(--muted);
        font-size: 16px;
        line-height: 1.6;
      }

      .stack {
        display: grid;
        gap: 18px;
        margin-top: 22px;
      }

      .panel {
        padding: 18px;
        border-radius: 20px;
        background: rgba(255, 255, 255, 0.04);
        border: 1px solid rgba(255, 255, 255, 0.08);
      }

      h2 {
        margin: 0 0 10px;
        font-size: 14px;
        letter-spacing: 0.14em;
        text-transform: uppercase;
        color: rgba(248, 250, 252, 0.68);
      }

      ul {
        margin: 0;
        padding-left: 18px;
        color: var(--text);
        line-height: 1.7;
      }

      a {
        color: inherit;
      }

      .link {
        display: inline-flex;
        margin-top: 16px;
        padding: 12px 16px;
        border-radius: 999px;
        background: linear-gradient(135deg, #fb923c, #f59e0b);
        color: #111827;
        font-weight: 700;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <main>
      <section class="card">
        <div class="eyebrow">Voice Note Studio</div>
        <h1>Bring voice notes into ChatGPT.</h1>
        <p>
          This app can work from pasted transcript text or public audio segment URLs from your recorder.
          The full transcript, structured summary, and WhatsApp-ready brief are returned in the tool result.
        </p>

        <div class="stack">
          <div class="panel">
            <h2>Use This Tool For</h2>
            <ul>
              <li>meeting recaps with action items and decisions</li>
              <li>Hindi, English, or mixed Hindi-English conversations</li>
              <li>public audio chunk URLs generated by the recorder app</li>
            </ul>
          </div>

          <div class="panel">
            <h2>Recorder App</h2>
            <p>Capture long conversations in the browser, then bring them into ChatGPT when you want a collaborative follow-up.</p>
            <a class="link" href="${appUrl}" target="_blank" rel="noreferrer">Open Voice Note Studio</a>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>`;
}

function withCors(response) {
  const headers = new Headers(response.headers);

  Object.entries(CORS_HEADERS).forEach(([key, value]) => {
    headers.set(key, value);
  });

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function buildResultText(result, appUrl) {
  const lines = ['Voice Note Studio brief ready.', '', result.summary];

  if (result.whatsappMessage) {
    lines.push('', 'WhatsApp Draft', result.whatsappMessage);
  }

  lines.push('', `Recorder app: ${appUrl}`);
  return lines.join('\n\n');
}

function createMcpServer(request) {
  const origin = new URL(request.url).origin;
  const appUrl = `${origin}/`;
  const server = new McpServer({
    name: APP_NAME,
    version: APP_VERSION,
  });

  registerAppResource(
    server,
    'Voice Note Studio Guide',
    TOOL_RESOURCE_URI,
    {
      description: 'A lightweight guide for using Voice Note Studio inside ChatGPT.',
    },
    async () => ({
      contents: [
        {
          uri: TOOL_RESOURCE_URI,
          mimeType: RESOURCE_MIME_TYPE,
          text: buildToolGuideHtml(appUrl),
        },
      ],
    })
  );

  registerAppTool(
    server,
    'analyze_voice_note',
    {
      title: 'Analyze Voice Note',
      description:
        'Create a transcript-based meeting brief from pasted transcript text or public audio URLs produced by Voice Note Studio.',
      inputSchema: {
        transcript: z
          .string()
          .optional()
          .describe('Optional raw transcript text. If present, this is used directly instead of transcribing audio.'),
        audioUrl: z
          .string()
          .url()
          .optional()
          .describe('Optional single public audio URL. Use this or audioUrls when you want transcription too.'),
        audioUrls: z
          .array(z.string().url())
          .max(MAX_AUDIO_CHUNKS)
          .optional()
          .describe(
            `Optional list of public audio URLs. Useful for long recordings that were uploaded in segments. Maximum ${MAX_AUDIO_CHUNKS} URLs.`
          ),
        language: z
          .enum(['auto', 'hi', 'en'])
          .optional()
          .describe('Language mode: auto for Hindi-English mixed speech, hi for Hindi, en for English.'),
        speechContext: z
          .string()
          .max(MAX_SPEECH_CONTEXT_CHARS)
          .optional()
          .describe('Optional spellings, people, company names, acronyms, or jargon to preserve accurately.'),
      },
      outputSchema: {
        sourceType: z.enum(['transcript', 'audio_urls']),
        transcript: z.string(),
        summary: z.string(),
        actionItems: z.array(z.string()),
        keyDecisions: z.array(z.string()),
        overview: z.string(),
        whatsappMessage: z.string(),
        language: z.enum(['auto', 'hi', 'en']),
        chunkCount: z.number().int().min(0),
        appUrl: z.string().url(),
      },
      _meta: {
        ui: {
          resourceUri: TOOL_RESOURCE_URI,
        },
      },
    },
    async ({ transcript, audioUrl, audioUrls, language, speechContext }) => {
      try {
        const mergedAudioUrls = [
          ...(audioUrl ? [audioUrl] : []),
          ...(Array.isArray(audioUrls) ? audioUrls : []),
        ];
        const result = await analyzeVoiceNote({
          transcript,
          audioUrls: mergedAudioUrls,
          language,
          speechContext,
        });
        const structuredContent = {
          ...result,
          appUrl,
        };

        return {
          content: [
            {
              type: 'text',
              text: buildResultText(result, appUrl),
            },
          ],
          structuredContent,
        };
      } catch (error) {
        const message = sanitizeProviderErrorMessage(
          error instanceof Error ? error.message : 'Unknown error processing voice note.'
        );

        return {
          isError: true,
          content: [
            {
              type: 'text',
              text: message,
            },
          ],
        };
      }
    }
  );

  return server;
}

async function handleRequest(request) {
  const transport = new WebStandardStreamableHTTPServerTransport();
  const server = createMcpServer(request);

  await server.connect(transport);

  const response = await transport.handleRequest(request);
  return withCors(response);
}

export async function GET(request) {
  return handleRequest(request);
}

export async function POST(request) {
  return handleRequest(request);
}

export async function DELETE(request) {
  return handleRequest(request);
}

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: CORS_HEADERS,
  });
}
